import importNewlines from "eslint-plugin-import-newlines";
import perfectionist from "eslint-plugin-perfectionist";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

export default [
  {
    ignores: ["node_modules", "styleguide.config.js"]
  },
  {
    files: ["**/*.{js,jsx}"],
    settings: {react: {version: "18.3"}},
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        sourceType: "module",
        ecmaFeatures: {
          arrowFunctions: true,
          binaryLiterals: true,
          blockBindings: true,
          classes: true,
          defaultParams: true,
          destructuring: true,
          forOf: true,
          generators: true,
          globalReturn: true,
          jsx: true,
          modules: false,
          objectLiteralComputedProperties: true,
          objectLiteralDuplicateProperties: true,
          objectLiteralShorthandMethods: true,
          objectLiteralShorthandProperties: true,
          octalLiterals: true,
          regexUFlag: true,
          regexYFlag: true,
          spread: true,
          superInFunctions: true,
          templateStrings: true,
          unicodeCodePointEscapes: true
        }
      }
    },
    plugins: {
      "import-newlines": importNewlines,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      perfectionist,
      react
    },
    rules: {
      "accessor-pairs": "warn",
      "array-bracket-spacing": "warn",
      "array-callback-return": "warn",
      "arrow-parens": ["warn", "as-needed", {requireForBlockBody: true}],
      "arrow-spacing": "warn",
      "block-scoped-var": "warn",
      "block-spacing": "warn",
      "brace-style": "warn",
      "callback-return": "warn",
      "comma-dangle": "error",
      "comma-spacing": "warn",
      "comma-style": "warn",
      "computed-property-spacing": "warn",
      "consistent-return": "off",
      "consistent-this": "warn",
      "constructor-super": "error",
      "default-case": "warn",
      "dot-location": ["warn", "property"],
      "dot-notation": "warn",
      "eol-last": "warn",
      "func-names": "warn",
      "func-style": "warn",
      "generator-star-spacing": "warn",
      "global-require": "warn",
      "guard-for-in": "warn",
      "handle-callback-err": "warn",
      "id-blacklist": "warn",
      "id-length": "off",
      "id-match": "warn",
      "import-newlines/enforce": ["warn", 1],
      "init-declarations": "warn",
      "jsx-quotes": "warn",
      "key-spacing": "warn",
      "keyword-spacing": "warn",
      "lines-around-comment": ["warn", {allowObjectStart: true}],
      "max-depth": "warn",
      "max-len": ["warn", {code: 146, ignorePattern: "\\s*<", ignoreTemplateLiterals: true}],
      "max-nested-callbacks": "warn",
      "max-params": ["warn", 5],
      "max-statements": ["warn", 40],
      "max-statements-per-line": "warn",
      "new-cap": "warn",
      "new-parens": "warn",
      "newline-after-var": "warn",
      "newline-before-return": "warn",
      "newline-per-chained-call": "warn",
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-bitwise": "warn",
      "no-caller": "warn",
      "no-case-declarations": "error",
      "no-catch-shadow": "warn",
      "no-class-assign": "error",
      "no-cond-assign": "error",
      "no-confusing-arrow": "off",
      "no-console": "warn",
      "no-const-assign": "error",
      "no-constant-condition": "error",
      "no-continue": "warn",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-div-regex": "warn",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "warn",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-function": "warn",
      "no-empty-pattern": "error",
      "no-eq-null": "warn",
      "no-eval": "warn",
      "no-ex-assign": "error",
      "no-extend-native": "warn",
      "no-extra-bind": "warn",
      "no-extra-boolean-cast": "error",
      "no-extra-label": "warn",
      "no-extra-parens": "warn",
      "no-extra-semi": "error",
      "no-fallthrough": "error",
      "no-floating-decimal": "warn",
      "no-func-assign": "error",
      "no-implicit-coercion": "warn",
      "no-implicit-globals": "warn",
      "no-implied-eval": "warn",
      "no-inline-comments": "warn",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-invalid-this": "off",
      "no-irregular-whitespace": "error",
      "no-iterator": "warn",
      "no-label-var": "warn",
      "no-labels": "warn",
      "no-lone-blocks": "warn",
      "no-lonely-if": "off",
      "no-loop-func": "warn",
      "no-magic-numbers": "off",
      "no-mixed-requires": "warn",
      "no-mixed-spaces-and-tabs": "error",
      "no-multi-spaces": "warn",
      "no-multi-str": "warn",
      "no-multiple-empty-lines": ["warn", {max: 1}],
      "no-native-reassign": "warn",
      "no-negated-condition": "warn",
      "no-negated-in-lhs": "error",
      "no-nested-ternary": "warn",
      "no-new": "warn",
      "no-new-func": "warn",
      "no-new-object": "warn",
      "no-new-require": "warn",
      "no-new-symbol": "error",
      "no-new-wrappers": "warn",
      "no-obj-calls": "error",
      "no-octal": "error",
      "no-octal-escape": "warn",
      "no-param-reassign": "warn",
      "no-path-concat": "warn",
      "no-plusplus": "off",
      "no-process-env": "off",
      "no-process-exit": "warn",
      "no-proto": "warn",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-restricted-globals": "warn",
      "no-restricted-imports": ["warn", {patterns: ["../*"]}],
      "no-restricted-modules": "warn",
      "no-restricted-syntax": "warn",
      "no-return-assign": "warn",
      "no-script-url": "warn",
      "no-self-assign": "error",
      "no-self-compare": "warn",
      "no-sequences": "warn",
      "no-shadow": "warn",
      "no-shadow-restricted-names": "warn",
      "no-spaced-func": "warn",
      "no-sparse-arrays": "error",
      "no-sync": "warn",
      "no-ternary": "off",
      "no-this-before-super": "error",
      "no-throw-literal": "warn",
      "no-trailing-spaces": "warn",
      "no-undef": "error",
      "no-undef-init": "warn",
      "no-undefined": "warn",
      "no-underscore-dangle": "warn",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "warn",
      "no-unneeded-ternary": "warn",
      "no-unreachable": "error",
      "no-unused-expressions": "warn",
      "no-unused-labels": "error",
      "no-unused-vars": ["warn", {args: "after-used", vars: "local"}],
      "no-use-before-define": "warn",
      "no-useless-call": "warn",
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-var": "warn",
      "no-void": "warn",
      "no-warning-comments": "warn",
      "no-whitespace-before-property": "warn",
      "no-with": "warn",
      "object-curly-spacing": ["warn", "never"],
      "object-shorthand": "warn",
      "one-var": "off",
      "one-var-declaration-per-line": "warn",
      "operator-assignment": "warn",
      "padded-blocks": ["warn", "never"],
      "perfectionist/sort-imports": [
        "warn",
        {
          environment: "node",
          ignoreCase: true,
          internalPattern: ["^@/.+"],
          newlinesBetween: "always",
          order: "asc",
          partitionByComment: false,
          partitionByNewLine: false,
          specialCharacters: "keep",
          type: "alphabetical",
          customGroups: {
            value: {
              mui: "^@mui",
              png: [".*png$", ".*png.react$"],
              react: ["^react$", "^react-.+"],
              svg: [".*svg$", ".*svg.react$"]
            }
          },
          groups: [
            "react",
            ["builtin", "external"],
            "mui",
            "internal",
            ["parent", "sibling", "index"],
            "object",
            "svg",
            "png",
            "unknown"
          ]
        }
      ],
      "perfectionist/sort-jsx-props": [
        "warn",
        {
          ignoreCase: true,
          ignorePattern: [],
          order: "asc",
          specialCharacters: "keep",
          type: "alphabetical",
          customGroups: {
            callback: "^on.+"
          },
          groups: [
            "shorthand",
            "unknown",
            "multiline",
            "callback"
          ]
        }
      ],
      "perfectionist/sort-named-imports": [
        "warn",
        {
          groupKind: "mixed",
          ignoreAlias: false,
          ignoreCase: true,
          order: "asc",
          partitionByComment: false,
          partitionByNewLine: false,
          specialCharacters: "keep",
          type: "alphabetical"
        }
      ],
      "perfectionist/sort-objects": [
        "warn",
        {
          ignoreCase: true,
          ignorePattern: [],
          newlinesBetween: "ignore",
          objectDeclarations: false,
          order: "asc",
          partitionByComment: false,
          partitionByNewLine: false,
          specialCharacters: "keep",
          styledComponents: true,
          type: "alphabetical",
          customGroups: {
            quoted: ".*-.*"
          },
          groups: [
            "quoted",
            "unknown",
            "multiline",
            "method"
          ]
        }
      ],
      "prefer-arrow-callback": "warn",
      "prefer-const": "warn",
      "prefer-reflect": "warn",
      "prefer-rest-params": "warn",
      "prefer-spread": "warn",
      "prefer-template": "warn",
      "quote-props": ["warn", "consistent-as-needed"],
      "react/jsx-closing-bracket-location": ["warn", {location: "tag-aligned"}],
      "react/jsx-closing-tag-location": ["warn", {location: "tag-aligned"}],
      "react/jsx-curly-spacing": ["warn", {
        allowMultiline: true,
        children: true,
        spacing: {objectLiterals: "never"},
        when: "never"
      }],
      "react/jsx-first-prop-new-line": "warn",
      "react/jsx-max-props-per-line": ["warn", {maximum: 1}],
      "react/jsx-no-undef": "error",
      "react/jsx-uses-react": "error",
      "react/jsx-uses-vars": "warn",
      "require-yield": "warn",
      "semi-spacing": "warn",
      "sort-imports": "off",
      "sort-vars": "off",
      "space-before-blocks": "warn",
      "space-before-function-paren": "warn",
      "space-in-parens": "warn",
      "space-infix-ops": "warn",
      "space-unary-ops": "warn",
      "spaced-comment": "warn",
      "template-curly-spacing": "warn",
      "use-isnan": "error",
      "valid-typeof": "error",
      "vars-on-top": "warn",
      "wrap-iife": "warn",
      "wrap-regex": "warn",
      "yield-star-spacing": "warn",
      "complexity": ["warn", 40],
      "curly": "warn",
      "eqeqeq": "warn",
      "indent": ["warn", 2],
      "quotes": "warn",
      "radix": "off",
      "semi": "warn",
      "strict": "warn",
      "yoda": "warn"
    }
  }
];
