name: Deploy SaraS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: milos1701/github-pages-deploy-action@v4
        with:
          branch: main
          folder: build
